### ISSUE TITLE
Invalid algorithm

### ISSUE THREAD

**Issue by viown** [Privanom/algorithms#1]
The bubble sort algorithm at [bubblesort.c](https://github.com/Privanom/algorithms/blob/main/bubblesort.c) seems to be specifically tailored to only work on arrays with the length of 10. If the array's size is less than 10, this causes a segmentation fault, and if it's higher than 10, the array may not be fully sorted. Additionally the arrays are chars and not integers, not sure if this was intended or not, but this array will be sorted in the terms of the ASCII key structure and not numbers.

A sorting algorithm has to be able to work with arrays of variable size, learn how and when to use for & while loops, and other features C provides to achieve this.
Good luck.

**Comment by Privanom** [comment]
Thanks, i am working on a new prototype. Didn't cross my mind.
