### ISSUE TITLE
Add O(n log n) sorting algorithms

### ISSUE THREAD

**Issue by ybrenning** [Privanom/algorithms#8]
**Is your feature request related to a problem? Please describe.**
Not related to any problem, just a new addition.

**Describe the solution you'd like**
I would like to add implementations of sorting algorithms with improved time complexity such as merge sort and quicksort.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Privanom** [comment]
I added a merge sort for now, may add a quick sort :)
