### ISSUE TITLE
Incorrect implementation of Merge Sort

### ISSUE THREAD

**Issue by ybrenning** [Privanom/algorithms#9]
**Describe the bug**
`mergesort.c` will not perform a valid sort upon the given array `yarray[]`. 
First of all, the length of the array `size_` is not calculated properly, it should rather be done like this:
```c
size_t len = sizeof(yarray) / sizeof(int);
```

In addition, the current function `mergesort()` is not a working implementation of the merge sort algorithm and does not produce a sorted array. Generally, merge sort is implemented using a function `merge()`, which merges two sorted subarrays and `merge_sort()`, which performs the sorting using recursive calls.

**To Reproduce**
Compile `mergesort.c` using Make or CMake

**Expected behavior**
The program should create an array and get its size, call the `mergesort()` function and print the sorted array.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Issues similar to this can be avoided by adding test functions/source files to the project along with a CMake and GitHub actions for CI.

**Comment by Privanom** [comment]
Thanks @ybrenning ! The issue has been fixed
